### ISSUE TITLE
check the definition

### ISSUE THREAD

**Issue by daimiao-chen** [daimiao-chen/Dictionary#2]
Users can check the definition

**Comment by NonyeAsogwa** [comment]
As a user, i will be able to put a word in the input text and click the search button to **check the definition**.

**Comment by OlegBaryshev94** [comment]
As a user, i will be able to put a word in the input text and click the search button **to check the definition**.

**Comment by daimiao-chen** [comment]
reopen this issue for adding a comment link
Nonye's working on that comment: 6c5a9ad
