### ISSUE TITLE
vocabulary test

### ISSUE THREAD

**Issue by daimiao-chen** [daimiao-chen/Dictionary#7]
Users can take a vocabulary test from their favorite list

**Comment by OlegBaryshev94** [comment]
As a user, I want to can find a "Have a Test" button in favourite list. Then application will show a screen for **vocabulary test**, in that screen, I can hear the pronunciation, and spell the vocabulary, the program will check my spelling and show the result. If it correct, will display a correct icon, if it wrong, it will show the correct words.
